### ISSUE TITLE
Solr 8.11.1 standalone, unable to install solritas

### ISSUE THREAD

**Issue by arvind-das** [erikhatcher/solritas#4]
I am getting this issue when I try to install win standalone mode. Installing with solr-cloud, it just works fine.
The exception is raised for zookeeper which is not running but the same does not happen with solr-cloud, zookeeper is not running for that mode too. 

```
org.apache.solr.common.SolrException: java.lang.NullPointerException
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:182)
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:119)
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:114)
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:101)
	at org.apache.solr.packagemanager.PackageManager.<init>(PackageManager.java:85)
	at org.apache.solr.util.PackageTool.runImpl(PackageTool.java:85)
	at org.apache.solr.util.SolrCLI$ToolBase.runTool(SolrCLI.java:196)
	at org.apache.solr.util.SolrCLI.main(SolrCLI.java:310)
Caused by: java.lang.NullPointerException
	at org.apache.zookeeper.client.ConnectStringParser.<init>(ConnectStringParser.java:54)
	at org.apache.zookeeper.ZooKeeper.createDefaultHostProvider(ZooKeeper.java:1515)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:1108)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:818)
	at org.apache.solr.common.cloud.SolrZooKeeper.<init>(SolrZooKeeper.java:44)
	at org.apache.solr.common.cloud.ZkClientConnectionStrategy.createSolrZooKeeper(ZkClientConnectionStrategy.java:109)
	at org.apache.solr.common.cloud.DefaultConnectionStrategy.connect(DefaultConnectionStrategy.java:37)
	at org.apache.solr.common.cloud.SolrZkClient.<init>(SolrZkClient.java:160)
	... 7 more

ERROR: java.lang.NullPointerException
```

Am I doing something wrong ?

Please suggest,
Thanks

**Comment by epugh** [comment]
I'm not sure if the install assumes solrcloud, however, if you just pass a `-c` to your standalone startup, it will use an embedded zookeeper.   I do this all the time on "standalone" setups to get the benefits of the better apis etc from solr cloud....

**Comment by erikhatcher** [comment]
This could be made to work standalone, by deploying the .jar files and using `<lib>` directives, but that is no longer documented/supported.
